services:
  db:
    image: postgres:15-alpine
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherdb
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: weather_redis
    restart: always
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: weather_app
    restart: on-failure
    env_file:
      - ./.env.example
    environment:
      # override DATABASE_URL to point at the postgres service
      DATABASE_URL: postgres://postgres:postgres@db:5432/weatherdb
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  db_data:
  redis_data:
